package protopkg

import (
	"flag"
	"fmt"
	"log"

	"github.com/bazelbuild/bazel-gazelle/config"
	gzflag "github.com/bazelbuild/bazel-gazelle/flag"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const protoPkgLanguageName = "protopkg"

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return &protoPkgLanguage{
		resolver: newResolver(),
	}
}

// protoPkgLanguage implements language.Language.
type protoPkgLanguage struct {
	protoRepositoryImportsFile []string
	resolver                   *resolver
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (pl *protoPkgLanguage) Name() string { return protoPkgLanguageName }

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (l *protoPkgLanguage) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.Var(&gzflag.MultiFlag{Values: &l.protoRepositoryImportsFile}, "proto_repository_imports_file", "path to a proto_repository imports.csv file")
}

func (l *protoPkgLanguage) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	c.Exts[protoPkgLanguageName] = newProtoPkgConfig(c)

	for _, filename := range l.protoRepositoryImportsFile {
		if err := l.resolver.LoadFile(filename); err != nil {
			return fmt.Errorf("loading proto_repository imports file %q: %w", filename, err)
		}
	}

	return nil
}

func (*protoPkgLanguage) KnownDirectives() []string {
	return []string{protoPkgPackageDirective}
}

// Configure implements config.Configurer
func (l *protoPkgLanguage) Configure(c *config.Config, rel string, f *rule.File) {
	// log.Println("configure:", rel)
	if f != nil {
		if err := l.getOrCreateProtoPkgConfig(c).ParseDirectives(rel, f.Directives); err != nil {
			log.Fatalf("parsing directives in package %q: %v", rel, err)
		}
	}
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*protoPkgLanguage) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		"protopkg_package": {
			ResolveAttrs: map[string]bool{"deps": true},
		},
	}
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (l *protoPkgLanguage) Loads() []rule.LoadInfo { return nil }

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*protoPkgLanguage) Fix(c *config.Config, f *rule.File) {}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (l *protoPkgLanguage) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*protoPkgLanguage) Embeds(r *rule.Rule, from label.Label) []label.Label { return nil }

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (l *protoPkgLanguage) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw interface{},
	from label.Label,
) {
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (l *protoPkgLanguage) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	log.Println("generate:", args.Rel)

	cfg := getProtoPkgConfig(args.Config)
	rules := cfg.rules(l.resolver)
	imports := make([]interface{}, len(rules))
	for i, r := range rules {
		imports[i] = r.PrivateAttr(config.GazelleImportsKey)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
		Empty:   cfg.empty(),
	}
}
