package protopkg

import (
	"github.com/bazelbuild/bazel-gazelle/language"
)

// NewLanguage creates a new protoPkgLang Gazelle extension implementation.
func NewLanguage() language.Language {
	return &protoPkgLang{}
}

// protoPkgLang implements language.Language.
type protoPkgLang struct {
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (pl *protoPkgLang) Name() string { return "protopkg" }
